### ISSUE TITLE
Где можно найти слайды выступлений?

### ISSUE THREAD

**Issue by alherd-by** [PHP-Belarus/php.of.by#23]

**Comment by vkhramtsov** [comment]
Пока нигде, я свои собираюсь выложить в понедельник куда-нибудь и поставить ссылку. А сейчас надо готовиться к выходным :)

**Comment by vkhramtsov** [comment]
Слайды моего выступления здаесь https://www.slideshare.net/secret/dZcJ703KAJQAkt

**Comment by vkhramtsov** [comment]
@volegg, можешь здесь отписать про viber?

**Comment by chilic** [comment]
#33 #34

**Comment by vkhramtsov** [comment]
Closed as obsolete
