### ISSUE TITLE
Неизвестна логика деплоя

### ISSUE THREAD

**Issue by Gormartsen** [PHP-Belarus/php.of.by#30]
Вот тут

https://github.com/PHP-Belarus/php.of.by/blob/master/bin/deploy-to-prod.sh#L11
Вызов файла который на удаленном сервере что то там делает.

Не понятно что, не известно как повторить.

**Comment by Gormartsen** [comment]
@vkhramtsov ?

**Comment by vkhramtsov** [comment]
Этот вопрос скорее надо адресовать @chilic , ибо это он писал этот скрипт, я сам не знаю что он там делает :smile: . Сам деплой проиходит при создании тега в репозитории. Насколько я могу предполагать, данный скрипт разворачивает на хостинге архив, но больше мне ничего не известно.

**Comment by chilic** [comment]
@Gormartsen @vkhramtsov это экспериментальный скрипт, не стоит на него сильно завязываться.

```bash
#!/bin/bash
cd `dirname $0`

# Extract the package
tar -xzf package.tgz
rm package.tgz

# Copy any file we want to keep from build to build
cp ~/php.of.by/config/parameters.yml ~/php.of.by/builds/build/app/config/parameters.yml

# Swap it all around, keeping the previous version aside in case something goes wrong
rm -rf build_old
mv current build_old
mv build current
```

**Comment by Gormartsen** [comment]
А deploy_* переменные я так понял вбиты в админке трависа?

**Comment by chilic** [comment]
@Gormartsen да, всё так. Переменные вида `$DEPLOY_*` - это переменные окружения travis-ci.

**Comment by Gormartsen** [comment]
@vkhramtsov @chillic спасибо. Понял.

Вопрос, вас двоих в скайп чате выловить реально?

Цель: мне надо понять и разобраться с тем какая у вас практика деплоя.

Я в целом понимаю цели деплоя через релизы и архивы но хочу услышать именно про методологию.

Я в основном работаю по другой методологии, когда доставка кода на продакшн идет через git pull ( с этим я съел целую стаю дохлых собак) 

Но вот деплой архивами, для меня не понятен. Хочу понять чем именно мотивирована и как именно внедрена.

Можно голосом даже.

Это все в контексте подготовки к следующему митапу, где я проведу целевой доклад пример по деплою php.of.by

**Comment by vkhramtsov** [comment]
Деплой архива хорош тем, что можно установить все зависимости и провести все подготовительные действия заранее(тесты, сжать и минифицировать js и css код и т.д.). Таким образом не надо держать гит на проде и к тому же можно сэкономить время в процессе деплоя. Что касается голосом, то либо в понедельник, либо после вторника. Мы живём в часовой зоне UTC + 3 (это чтобы можно было чётко рассчитывать время).

**Comment by Gormartsen** [comment]
Владимир,

Это я как раз понимаю.
Тут больше вопрос к:
- как разворачивается архив и в особенности с учетом данных что были сохранены из веб(картинки залитые через форму к примеру) или локально зависимых конфигов (пути к временным папкам, директориям с кешем и тп)
Пример решения: директории для веб файлов залитых через веб прописана вне директории билда. 
- как решаются проблемы изменения и отката зависимых ресурсов: базы данных, настроек solr, sphinxsearch.
- особенности реализации qa , включая staging , тестирование билда на целостность и работа с заказчиком на ранней стадии ( показать продукт до релиза)

**Comment by vkhramtsov** [comment]
- Данные, которые были залиты через веб, хранятся по дургим путям, которые с билдом ничего общего не имеют. Они подключаются к билду через symlinks. Таким образом, билд вообще ничего из этих данных не трогает, кроме случаев, когда требуется преобразование этих данных. Поскольку у нас таких данных пока нет, то и механизм у нас не построен. Что касается конфигов, то просто  создаётся готовый конфиг для разных площадок, а дальше по вкусу. Либо включение (include or import) конфига в зависимости от площадки, либо просто сбор всех нужных настроек в отдельный конфиг, который потом устанавливается вместе с билдом. 
- Что касается отката базы -- её у нас пока нет, однако пока планируется использование doctrine migrations, которая обеспечивает как обновление, так и откат базы (всё конечно зависит от того, насколько хорошо написаны миграции :smile: ). Что касается других сервисов, то здесь могут быть два варианта: либо мы храним конфиги вместе с билдом, либо выкатывать их отдельно с помощью devops tools. На данный момент перед нами данная проблема не стоит, поэтому сказать что-то конкретное не представляется возможным.
- по поводу особенностей реализаций QA, staging, etc -- не совсем понятен вопрос. Показать билд заказчику можно как на QA, так и на staging. Главное чтобы при тестировании туда не вносились неоднозначные данные, например неполиткорректные картинки и фразы :smile:

**Comment by Gormartsen** [comment]
Php.of.by тут больше как пример реализации. Это де не первая проба пера? Тоесть есть уже опыт реализации именно таким подходом. Вот к нему я и мосты навожу.

Миграция через доктрину я так понимаю помогает решать вопрос схемы данных?

А что делать с данными?
Решались ли проблемы ранее вами как откат не только схемы базы но и данных?

По qa и stage, они релизятся как? Или нет практикивыката билдов на каждый коммит, PR, branch, с созданием отдельного тестового образа системы, который может пощупать как заказчик так и project manager?

Напомню - это все в контексте подготовки к докладу.
У меня целостная методология разработки, но я хочу вкурить особенности и главное опыт работы с билдами. Вдруг я сто упускаю.

**Comment by vkhramtsov** [comment]
По поводу данных: если есть данные, которые общие для проекта в принципе, такие как конфигурационная таблица или что-то вроде этого, то это решается той же доктриной. Если мы говорим о тестовых данных, то здесь нам помогут fixtures. 
QA может релизиться из мастера, stage -- только из стабильной ветки, на то он и stage. Практики выката билдов на каждый PR нет, иначе тогда у команды тестирования возникают проблемы с пониманием, что они сейчас тестируют. Также может быть проблема в том, что будет выкатываться бид для нового PR, в то время, как идёт тестирование другого функционала.

**Comment by Gormartsen** [comment]
Ага, спасибо @vkhramtsov по немногу начинаю видеть ваш опыт и специфику.

Я имел ввиду боевые данные. Если брать за пример cms состовляющую - то контент страниц Аля записи в блоге? Если брать crm- то база клиентов, профили, завязанные данные как то: заказы оплаты и тому подобная специфика.

Верно понимаю что по сути тестирование организовано с за вязкой на бран и тестирование идет бранча. Потом идет freeze разработки перед релизом, что б вдруг новые баги не попали , пока qa отдел до проверяет все, покажет заказчику, получит апрув на релиз и его выкатку?

И как эти проблемы решаете или оставляете как часть рабочего процесса?

Сразу прошу сказать если ошибся с анализом подспудных проблем такой практики и на практике не так.

**Comment by vkhramtsov** [comment]
Если касаться боевых данных, то если вам  надо просто их внести а забыть о связи, то их можно вставить и в миграцию. Если вам надо как-то сохранять связи и т.д., то тут надо придумывать какой-то обходной способ.

Конкретно у нас пока тестирования нет. У нас только одна страница. Но вообще я говорил о чем-то подобном.
У вас вопросы не о настоящем нашего проекта, а о его дальнем будущем.

**Comment by Gormartsen** [comment]
@vkhramtsov я больше вопросы задаю нацеливаясь не на этот проект а на ваш опыт в других проектах. В целом я более менее разобрался. Сейчас перевариваю информацию и сделаю адаптивный CI&CD на zen.ci с учетом особенностей и по этому материалу подготовлю детальный доклад на митап в начале июля?

**Comment by vkhramtsov** [comment]
Я посмотрел на ваш сервис. На мой взгля, на нём крайне не хватает документации, поэтому судить о его возможностях крайне трудно. При этом некоторые ссылки ведут на 404. Как пример, ссылка на странице http://docs.zen.ci/Getting%20started/Configuring%20.zenci.yml ссылка в предложении `box - See more details about it here` (под here).

**Comment by Gormartsen** [comment]
Спасибо @vkhramtsov ! Поправим.

Над документацией в плотную работаем.
Какраз подготовка к митапу, упадет ввиду примеров в документацию по работе с симфони и композером.

Кстати если есть желание, можете посмотреть в реальности работу PR деплоя .
Форкните репо https://github.com/Zen-CI/docs.zen.ci
Измените ссылки в Documentation папке в соответствующем файле и отошлите PR

Создаст сайт на основе ваших изменений.
Адрес можно будет увидеть в деплой логе.
Надо будет его в статус вынести кстати.

**Comment by vkhramtsov** [comment]
Судя по всему, ближайший митап будет в августе (пока не на 100%). Что касается документации, то только по ней можно сделать какие-то выводы, иначе, даже о возможностях, которые никто кроме вас не предлагает, узнать невозможно. 
Что касается форка и PR, то к сожалению сейчас времени на то, чтобы поиграться, у меня пока нет.
