### ISSUE TITLE
Investigate which tags implementation we can use

### ISSUE THREAD

**Issue by chilic** [PHP-Belarus/php.of.by#35]
- https://github.com/FabienPennequin/FPNTagBundle
- https://github.com/netgen/TagsBundle
- Custom implementation?

**Comment by vkhramtsov** [comment]
Looks like https://github.com/FabienPennequin/FPNTagBundle is dead. https://github.com/netgen/TagsBundle needs  eZ Publish. I think that we need to find something else.

**Comment by chilic** [comment]
@vkhramtsov I suggest custom implementation.
