### ISSUE TITLE
Add EasyAdminBundle

### ISSUE THREAD

**Issue by chilic** [PHP-Belarus/php.of.by#36]

**Comment by vkhramtsov** [comment]
Ok, we can try with this bundle. It looks like we have to alternatives:
- https://packagist.org/packages/javiereguiluz/easyadmin-bundle
- https://packagist.org/packages/madrakio/easy-admin-bundle
First one is more popular and mature.

Who will be in charge for this?
It looks like we need perform next steps during implementing this task: 
- choose database engine
- update documentation(install `PDO` and proper driver)
- check `doctrine` and `doctrine migrations`
- update buildplan to validate DB schema and migrations during the build
- update buildplan to apply database migrations during deploy

**Comment by chilic** [comment]
@vkhramtsov I created issues for this. Engine for now is MySQL.

**Comment by vkhramtsov** [comment]
I will add https://packagist.org/packages/javiereguiluz/easyadmin-bundle to our project

**Comment by vkhramtsov** [comment]
Here I'm only adding bundle. First of all we need to implement functionality, described in #1, because we need to restrict access to admin part of site. Also we need to keep in mind that we need to manage users. So we can create integration according to documentation.
