### ISSUE TITLE
Build failed with message build.xml:68:27: "rst2html" not found

### ISSUE THREAD

**Issue by chilic** [PHP-Belarus/php.of.by#4]
Run command:
`php phing.phar`

Error message:
```
build.xml:68:27: "rst2html" not found. Install python-docutils.
```

How we can fix this? We really need html docs?

**Comment by vkhramtsov** [comment]
* What do you use as build server?
* What ci server do you use?
* Do you have all required packages installed?

Anyway, I can create separate build plan without tasks related to documentation.

**Comment by chilic** [comment]
Closed for now.
