### ISSUE TITLE
update buildplan to apply database migrations during deploy

### ISSUE THREAD

**Issue by chilic** [PHP-Belarus/php.of.by#40]

**Comment by vkhramtsov** [comment]
@chilic  Where should we place migrations execution? There are two options:
- `deploy-to-prod.sh`
- script, which called to deploy code on production `$DEPLOY_PATH/deploy.sh`

**Comment by chilic** [comment]
@vkhramtsov I prefer keep migration in `https://github.com/PHP-Belarus/php.of.by/blob/master/bin/deploy-to-prod.sh`. Is this make sense?

**Comment by vkhramtsov** [comment]
@chilic Updated, please check
