### ISSUE TITLE
Need to set up deploy vars for prod DB access on https://travis-ci.org/

### ISSUE THREAD

**Issue by vkhramtsov** [PHP-Belarus/php.of.by#49]
Please define next variables:
- `DEPLOY_DB_HOST`
- `DEPLOY_DB_NAME`
- `DEPLOY_DB_USER`
- `DEPLOY_DB_PASSWORD`

**Comment by chilic** [comment]
@vkhramtsov Done.

**Comment by vkhramtsov** [comment]
@chilic  Thank you. I will try to deploy our code to prod during weekend.
